# Generated by Django 4.0.4 on 2022-06-03 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('bb', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=2000)),
                ('label', models.CharField(max_length=100)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e04.database')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TR', 'Train'), ('RE', 'Retrieval'), ('DE', 'Detection'), ('RD', 'Retrieval and Detection')], max_length=2)),
                ('status', models.CharField(choices=[('PR', 'Processing'), ('FI', 'Finished'), ('PD', 'Pending'), ('ER', 'Error')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('frame', models.IntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e04.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('value', models.FloatField()),
                ('imagedb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e04.imagedb')),
                ('processed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e04.processed')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('BB', 'Bounding Box'), ('SC', 'Score'), ('LB', 'Label')], max_length=2)),
                ('value', models.CharField(max_length=100)),
                ('processed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e04.processed')),
            ],
        ),
        migrations.CreateModel(
            name='OpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('DB', 'Database'), ('RC', 'Retrieval Confidence'), ('DC', 'Detection Confidence'), ('EP', 'Train Epoch')], max_length=2)),
                ('value', models.CharField(max_length=100)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e04.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FA', 'Face'), ('OB', 'Object')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('model_path', models.CharField(max_length=255)),
                ('val_acc', models.FloatField()),
                ('op_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e04.operation')),
            ],
        ),
        migrations.AddField(
            model_name='imagedb',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e04.operation'),
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_pre_process', models.CharField(choices=[('DE', 'Default'), ('MT', 'MTCNN'), ('SP', 'SphereFace'), ('OP', 'OpenFace')], max_length=2)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('det_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='det_model', to='e04.model')),
                ('ret_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ret_model', to='e04.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['processed_id', 'imagedb_id'], name='e04_ranking_process_044ad6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('processed_id', 'imagedb_id'), name='ranking_ids'),
        ),
    ]
