# Generated by Django 4.0.4 on 2022-06-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e04', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='save_path',
            field=models.CharField(default='/home', max_length=200),
        ),
    ]
