# Generated by Django 4.0.4 on 2022-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e04', '0002_generalconfig_save_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('TR', 'Train'), ('RE', 'Retrieval'), ('DE', 'Detection'), ('UD', 'Update DB'), ('RD', 'Retrieval and Detection')], max_length=2),
        ),
    ]
