# Generated by Django 4.0.4 on 2022-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e04', '0003_alter_database_quantity_alter_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='feature_mean',
            field=models.FloatField(default=0),
        ),
    ]
