# Generated by Django 4.0.4 on 2022-06-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e04', '0004_database_feature_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedb',
            name='features',
            field=models.CharField(max_length=12000),
        ),
    ]
