# Generated by Django 4.0.5 on 2022-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e04', '0005_alter_imagedb_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='obj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='database',
            name='feature_mean',
            field=models.CharField(default='0', max_length=12000),
        ),
    ]
