# Generated by Django 4.0.5 on 2022-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e04', '0006_output_obj_alter_database_feature_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('TR', 'Treino'), ('RE', 'Recuperação'), ('DE', 'Detecção'), ('UD', 'Update DB'), ('RD', 'Recuperação e Detecção')], max_length=2),
        ),
    ]
